kind: pipeline
name: default

steps:
  - name: docker
    image: plugins/docker
    environment:
      TOKEN: token
    settings:
      username: kaddopur
      password:
        from_secret: docker_password
      repo: kaddopur/drone
      dry_run: true
      tags: latest
      build_args_from_env:
        - TOKEN
