kind: pipeline
name: default

steps:
  - name: docker
    image: plugins/docker
    settings:
      username: docker_username
      password: docker_password
      repo: kaddopur/drone
      dry_run: true
      tags: latest
      build_args:
        - AUTH_KEY_ARG=http://yourproxy.com
