pipeline:
  build:
    image: node
    commands:
      - npm install
      - npm test
  publish:
    image: plugins/docker
    repo: kaddopur/drone
    secrets: [docker_username, docker_password]
    dry_run: true
